import { Dayjs } from "dayjs";
import { CardHistoryState } from "./CardHistoryEntity";
import { CardStatus } from "./Common";
import { AccountState } from "./AdditionalInfoEntity";
import { OperationState } from "./OperationEntity";

export type PersonCardState = {
  id?: string;
  createDate?: string;
  personStatus?: CardStatus;
  lastName?: string;
  firstName?: string;
  patrName?: string;
  reasonCredit?: string;
  birthDate?: Dayjs;
  companyName?: string;
  companyNumber?: number;
  companyInn?: number;
  companyDirectorName?: string;
  companyCountry?: { label: string; value: string };
  postAddress?: string;
  lawAddress?: string;
  companyRegistrationDate?: Dayjs;
  passportSerialNumber?: number;
  passportNumber?: number;
  issuedBy?: string;
  factAddress?: string;
  addressOfResidence?: string;
  history: CardHistoryState[];
  operations: OperationState[];
  accounts: AccountState[];
  photo?: Blob;
};
