export const tableDataMock = [
  {
    id: "ФЛ123011",
    status: "Новая",
    creditHistoryResult: true,
    lastName: "Сон",
    firstName: "Кирилл",
    patrName: "Романович",
    createDate: "2023-05-15",
  },
  {
    id: "ФЛ123010",
    status: "Новая",
    creditHistoryResult: false,
    lastName: "Акула",
    firstName: "Артем",
    patrName: "Артёмович",
    createDate: "2023-05-15",
  },
  {
    id: "ФЛ123009",
    status: "Новая",
    creditHistoryResult: true,
    lastName: "Горемыкина",
    firstName: "Юлия",
    patrName: "Кирилловна",
    createDate: "2023-05-14",
  },
  {
    id: "ФЛ123008",
    status: "Новая",
    creditHistoryResult: true,
    lastName: "Чач",
    firstName: "Артур",
    patrName: "Бибович",
    createDate: "2023-05-13",
  },
  {
    id: "ФЛ123007",
    status: "В работе",
    creditHistoryResult: true,
    lastName: "Пономарёва",
    firstName: "Мария",
    patrName: "Алексеевна",
    createDate: "2023-04-30",
  },
];
